apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rest-service
  - flight-service

configMapGenerator:
- name: dch-params
  envs:
  - params.env

replacements:
- source:
    kind: ConfigMap
    name: dch-params
    fieldPath: data.RELATED_IMAGE_ODH_DATA_CONNECT_HUB_REST_IMAGE
  targets:
  - select:
      kind: Deployment
      name: rest-service
    fieldPaths:
    - spec.template.spec.containers.[name=rest-service].image
- source:
    kind: ConfigMap
    name: dch-params
    fieldPath: data.RELATED_IMAGE_ODH_DATA_CONNECT_HUB_FLIGHT_IMAGE
  targets:
  - select:
      kind: Deployment
      name: flight-service
    fieldPaths:
    - spec.template.spec.containers.[name=flight-service].image
