[package]
name = "kube-utils"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
commons = { workspace = true }
kube = { workspace = true }
k8s-openapi = { workspace = true }
moka = { workspace = true, features = ["future"] }
tracing = { workspace = true }
