FROM registry.access.redhat.com/ubi9/go-toolset:1.26 AS builder

USER root
WORKDIR /workspace

COPY dc-controller/go.mod dc-controller/go.sum ./
RUN go mod download

COPY dc-controller/ .

RUN CGO_ENABLED=0 GOOS=linux go build -a -o manager cmd/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7@sha256:d91be7cea9f03a757d69ad7fcdfcd7849dba820110e7980d5e2a1f46ed06ea3b
WORKDIR /

COPY --from=builder --chown=root:root --chmod=0555 /workspace/manager .
COPY config/ /manifests/

USER 1001:1001

ENTRYPOINT ["/manager"]
