apiVersion: dataconnecthub.opendatahub.io/v1alpha1
kind: DataConnectService
metadata:
  labels:
    app.kubernetes.io/name: dc-controller
    app.kubernetes.io/managed-by: kustomize
  name: dataconnectservice-sample
spec:
  description: "Sample Data Connect Hub deployment"
  database:
    devMode: true
  gateway:
    name: odh-gateway
    namespace: opendatahub
  restService: {}
  flightService: {}
