name: OCI
provider: oci
description: OCI-compatible container registry
credentials_fields:
  - name: .dockerconfigjson
    label: Docker config json
    description: Docker config json file
    required: true
    type: string
  - name: OCI_HOST
    label: Oci host name
    description: OCI resgitry host name
    required: true
    type: string

