name: URI
provider: uri
description: Generic URI data source
credentials_fields:
  - name: URI
    label: Uri
    description: Data source URI
    required: true
    type: string
  - name: TOKEN
    label: Token authentication
    description: Authentication method for bearer token authentication
    required: false
    type: string
  - name: BASIC
    label: Basic
    description: The base64 encoded username:password for basic authentication
    required: false
    type: string

