controllerManager:
  image:
    repository: ghcr.io/opendatahub-io/data-connect-hub/dc-controller
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

relatedImages:
  restService: ghcr.io/opendatahub-io/data-connect-hub/rest-service:latest
  flightService: ghcr.io/opendatahub-io/data-connect-hub/flight-service:latest

leaderElection: true
