controllerManager:
  image:
    repository: ghcr.io/opendatahub-io/data-connect-hub/dc-controller
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

relatedImages:
  restService: ghcr.io/opendatahub-io/data-connect-hub/rest-service:latest
  flightService: ghcr.io/opendatahub-io/data-connect-hub/flight-service:latest
  kubeRbacProxy: quay.io/opendatahub/odh-kube-rbac-proxy@sha256:db643f5de15c0aab3eac9c60dc4cb311007f6977f96a790031b108f5c44a17d3

leaderElection: true

# operandNamespace: ""  # defaults to the controller's namespace if unset

dataConnectService:
  enabled: true

  restService: {}
    # image: "ghcr.io/opendatahub-io/data-connect-hub/rest-service:latest"
    # replicas: 1
    # resources:
    #   requests:
    #     cpu: "100m"
    #     memory: "256Mi"
    #   limits:
    #     cpu: "1"
    #     memory: "512Mi"
    # env:
    #   - name: RUST_LOG
    #     value: debug
    # envFrom: []
    # volumes: []
    # volumeMounts: []
    # imagePullSecrets:
    #   - name: my-pull-secret

  flightService: {}
    # image: "ghcr.io/opendatahub-io/data-connect-hub/flight-service:latest"
    # replicas: 1
    # resources:
    #   requests:
    #     cpu: "100m"
    #     memory: "256Mi"
    #   limits:
    #     cpu: "1"
    #     memory: "512Mi"
    # env:
    #   - name: RUST_LOG
    #     value: debug
    # envFrom: []
    # volumes: []
    # volumeMounts: []
    # imagePullSecrets:
    #   - name: my-pull-secret

  gateway: {}
    # name: odh-gateway
    # namespace: opendatahub
