apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-service-kube-rbac-proxy-config
  labels:
    app.kubernetes.io/name: rest-service
    app.kubernetes.io/part-of: data-connect-hub
data:
  config-file.yaml: |
    authorization:
      rewrites:
        byHttpHeader:
          name: X-Tenant-Id
      resourceAttributes:
        namespace: "{{ .Value }}"
        apiGroup: dataconnecthub.opendatahub.io
        resource: data-connections
        verb: get
