apiVersion: v1
kind: Service
metadata:
  name: rest-service
  labels:
    app.kubernetes.io/name: rest-service
    app.kubernetes.io/part-of: data-connect-hub
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rest-service
  ports:
    - name: https
      port: 8443
      targetPort: https