controllerManager:
  image:
    repository: quay.io/opendatahub/odh-data-connect-hub-controller
    tag: odh-stable
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

relatedImages:
  restService: quay.io/opendatahub/odh-data-connect-hub-rest:odh-stable
  flightService: quay.io/opendatahub/odh-data-connect-hub-flight:odh-stable
  kubeRbacProxy: quay.io/opendatahub/odh-kube-rbac-proxy:odh-stable

leaderElection: true
