[workspace]

[package]
name = "custom-connector"
version = "0.1.0"
edition = "2024"

[lints.rust]
unsafe_code = "deny"

[dependencies]
anyhow = "1.0"
arrow-flight = { version = "59.1.0", features = ["flight-sql"] }
async-trait = "0.1"
clap = { version = "4.6", features = ["derive"] }
commons = { path = "../../libs/commons" }
flight-service = { path = "../../services/flight", default-features = false }
kube-utils = { path = "../../libs/kube-utils" }
pg-meta-store = { path = "../../libs/pg-meta-store" }
rustls = { version = "0.23", default-features = false, features = ["aws_lc_rs"] }
tokio = { version = "1.52", features = ["rt-multi-thread", "macros", "signal"] }
tonic = "0.14"
tracing = "0.1"
