[database]
url = "postgresql://dch_user:dch_password@localhost:5432/dch_db"

[server]
address = "127.0.0.1"
port = 50051

[ingestion_cache_pools]
max_capacity = 50
ttl_secs = 30
idle_secs = 30

[query]
batch_size = 512
max_rows = 1000000