apiVersion: v1
kind: ConfigMap
metadata:
  name: flight-service-config
  labels:
    app.kubernetes.io/name: flight-service
    app.kubernetes.io/part-of: data-connect-hub
data:
  config.toml: |
    [server]
    address = "0.0.0.0"
    port = 50051

    [ingestion_cache_pools]
    max_capacity = 50
    ttl_secs = 30
    idle_secs = 30

    [tls]
    cert_file = "/etc/tls/private/tls.crt"
    key_file = "/etc/tls/private/tls.key"

    [auth]
    enabled = true
    cache_ttl_secs = 60

    [metrics]
    enabled = true
    address = "0.0.0.0"
    port = 9090

    [global-connection-types]
    tenant-id = "opendatahub"
