apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read
rules:
  - apiGroups: ["dataconnecthub.opendatahub.io"]
    resources: ["data-connections", "data-connection-types"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-write
rules:
  - apiGroups: ["dataconnecthub.opendatahub.io"]
    resources: ["data-connections", "data-connection-types"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "post", "put"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin
rules:
  - apiGroups: ["dataconnecthub.opendatahub.io"]
    resources: ["data-connections", "data-connection-types"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "post", "put"]
