apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - data-clusterrole.yaml
  - data-clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - service_account.yaml
  - networkpolicy.yaml
