resources:
- manager.yaml
- platform-config.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/opendatahub/odh-data-connect-hub-controller
  digest: sha256:67c7071ee6b4ece43861be704aabf4751186c976de6bf9b25191e71ed3ba60eb
