apiVersion: v1
kind: ConfigMap
metadata:
  name: opendatahub-dataconnecthub-config
  labels:
    platform.opendatahub.io/managed: "true"
data:
  distribution.name: Standalone
  distribution.version: 0.0.0
  controller.log.level: info
  gateway.name: odh-gateway
  gateway.namespace: opendatahub
